/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Dialog for editing a searchbot
 * @author Frank Weber
 */
public class EditSearchbotDialog extends javax.swing.JDialog {

    private String botname, link;
    private ArrayList<String> emails = new ArrayList();
    private int interval;
    private boolean pressedOK=false;
    /**
     * Creates new form AddSearchbotDialog
     */
    public EditSearchbotDialog(java.awt.Frame parent, boolean modal, String botName, String link, int interval, ArrayList<String> emails) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setSearchbot(botName, link, interval, emails);
    }
    
    private void setSearchbot(String botName, String link, int interval, ArrayList<String> emails){
        this.botname=botName;
        tfBotname.setText(botName);
        this.link=link;
        tfLink.setText(link);
        this.interval=interval;
        spInterval.setValue(interval);
        this.emails=emails;
        StringBuilder string = new StringBuilder();
        for (String email : emails) {
            string.append(email + ",");
        }
        tfEmails.setText(string.toString());
    }

    public boolean pressedOK() {
        return pressedOK;
    }
    
    public String getBotname() {
        return botname;
    }

    public String getLink() {
        return link;
    }

    public ArrayList<String> getEmails() {
        return emails;
    }

    public int getInterval() {
        return interval;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfLink = new javax.swing.JTextArea();
        tfBotname = new javax.swing.JTextField();
        lbBotname = new javax.swing.JLabel();
        lbLink = new javax.swing.JLabel();
        lbInterval = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfEmails = new javax.swing.JTextArea();
        pEmailText = new javax.swing.JPanel();
        lbEmails = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pInterval = new javax.swing.JPanel();
        spInterval = new javax.swing.JSpinner();
        lbSeconds = new javax.swing.JLabel();
        pButtons = new javax.swing.JPanel();
        btAddBot = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Searchbot");

        pMain.setLayout(new java.awt.GridBagLayout());

        tfLink.setColumns(20);
        tfLink.setRows(5);
        jScrollPane1.setViewportView(tfLink);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(jScrollPane1, gridBagConstraints);

        tfBotname.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(tfBotname, gridBagConstraints);

        lbBotname.setText("Botname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(lbBotname, gridBagConstraints);

        lbLink.setText("Searchinterval:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(lbLink, gridBagConstraints);

        lbInterval.setText("Willhaben-Link:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(lbInterval, gridBagConstraints);

        tfEmails.setColumns(20);
        tfEmails.setRows(5);
        jScrollPane2.setViewportView(tfEmails);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(jScrollPane2, gridBagConstraints);

        pEmailText.setLayout(new java.awt.GridLayout(2, 0));

        lbEmails.setText("Emails to send Notification:");
        pEmailText.add(lbEmails);

        jLabel1.setText("(separate with new line)");
        pEmailText.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(pEmailText, gridBagConstraints);

        spInterval.setModel(new javax.swing.SpinnerNumberModel(40, 40, 3600, 10));
        pInterval.add(spInterval);

        lbSeconds.setText("seconds");
        pInterval.add(lbSeconds);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pMain.add(pInterval, gridBagConstraints);

        btAddBot.setText("Change Botconfig");
        btAddBot.setFocusPainted(false);
        btAddBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onChangeSearchbot(evt);
            }
        });
        pButtons.add(btAddBot);

        btCancel.setText("Cancel");
        btCancel.setFocusPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        pButtons.add(btCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        pMain.add(pButtons, gridBagConstraints);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    private void onChangeSearchbot(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onChangeSearchbot
        try {
            if(tfBotname.getText().isEmpty()){
                throw new Exception("Botname is empty");
            }else{
                botname=tfBotname.getText();
                if(tfLink.getText().isEmpty()){
                    throw new Exception("Link is empty");
                }else{
                    link=tfLink.getText();
                    if(tfEmails.getText().isEmpty()){
                        throw new Exception("Email is empty");
                    }else{
                        emails.clear();
                        emails.add(tfEmails.getText());
                    }
                }
            }
            interval=(Integer)spInterval.getValue();
            pressedOK=true;
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onChangeSearchbot


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddBot;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBotname;
    private javax.swing.JLabel lbEmails;
    private javax.swing.JLabel lbInterval;
    private javax.swing.JLabel lbLink;
    private javax.swing.JLabel lbSeconds;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pEmailText;
    private javax.swing.JPanel pInterval;
    private javax.swing.JPanel pMain;
    private javax.swing.JSpinner spInterval;
    private javax.swing.JTextField tfBotname;
    private javax.swing.JTextArea tfEmails;
    private javax.swing.JTextArea tfLink;
    // End of variables declaration//GEN-END:variables
}
