/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.data.AuthenticationMethodEnum;
import gui.data.ConnectionSecurityEnum;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 * Dialog for editing the server email settings
 * @author Frank Weber
 */
public class UserSettingsDialog extends javax.swing.JDialog {

    private boolean pressedOK=false;
    private final String username;
    private String password;
    /**
     * Creates new form EmailSettingsDialog
     */
    public UserSettingsDialog(java.awt.Frame parent, boolean modal, String username, String password) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.username=username;
        this.password=password;
        lbUsername.setText(username);
    }
    
    public boolean pressedOK(){
        return pressedOK;
    }
    
    public String getNewPassword(){
        return password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        lbChangeUsername = new javax.swing.JLabel();
        lbOldPassword = new javax.swing.JLabel();
        tfOldPassword = new javax.swing.JPasswordField();
        lbUsername = new javax.swing.JLabel();
        lbNewPassword = new javax.swing.JLabel();
        tfNewPassword = new javax.swing.JPasswordField();
        tfRetypePassword = new javax.swing.JPasswordField();
        lbRetypePassword = new javax.swing.JLabel();
        pButtons = new javax.swing.JPanel();
        btOkay = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email settings");

        pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pMain.setLayout(new java.awt.GridBagLayout());

        lbChangeUsername.setText("Change password for user:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(lbChangeUsername, gridBagConstraints);

        lbOldPassword.setText("Old password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(lbOldPassword, gridBagConstraints);

        tfOldPassword.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(tfOldPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(lbUsername, gridBagConstraints);

        lbNewPassword.setText("New password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(lbNewPassword, gridBagConstraints);

        tfNewPassword.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(tfNewPassword, gridBagConstraints);

        tfRetypePassword.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(tfRetypePassword, gridBagConstraints);

        lbRetypePassword.setText("Retype password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(lbRetypePassword, gridBagConstraints);

        btOkay.setText("Change Password");
        btOkay.setFocusPainted(false);
        btOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkay(evt);
            }
        });
        pButtons.add(btOkay);

        btCancel.setText("Cancel");
        btCancel.setFocusPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        pButtons.add(btCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pMain.add(pButtons, gridBagConstraints);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onOkay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOkay
        try {
            System.out.println("Old: "+password);
            if(tfOldPassword.getPassword().equals(password)){
                //TODO Password regex validation
                if(tfNewPassword.getPassword().equals(tfRetypePassword.getPassword())){
                    password=tfNewPassword.getPassword().toString();
                }
            }
            pressedOK=true;
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onOkay

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOkay;
    private javax.swing.JLabel lbChangeUsername;
    private javax.swing.JLabel lbNewPassword;
    private javax.swing.JLabel lbOldPassword;
    private javax.swing.JLabel lbRetypePassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pMain;
    private javax.swing.JPasswordField tfNewPassword;
    private javax.swing.JPasswordField tfOldPassword;
    private javax.swing.JPasswordField tfRetypePassword;
    // End of variables declaration//GEN-END:variables
}
